#' Work In Data Schema
#'
#' Make an Arrow schema to read the Work In Data files.
#'
#' @param original If \code{TRUE}, returns the schema of the original
#' format, rather than that of the reformatted dataset.
#' @return An Arrow \code{\link[arrow]{schema}}.
#' @examples
#' wid_schema()
#' @export

wid_schema <- function(original = FALSE) {
  if (original) {
    arrow::schema(list(
      country = arrow::string(),
      survey_year = arrow::int16(),
      survey_period = arrow::string(),
      wgt = arrow::float32(),
      panel_wgt = arrow::float32(),
      gadm_1 = arrow::string(),
      gadm_2 = arrow::string(),
      ea = arrow::string(),
      density = arrow::float32(),
      rural = arrow::int8(),
      id_hh = arrow::string(),
      id_hh_panel = arrow::string(),
      id_ind = arrow::string(),
      id_ind_panel = arrow::string(),
      n_interview = arrow::int32(),
      n_ind_household = arrow::int16(),
      position = arrow::int8(),
      age = arrow::int32(),
      birth_day = arrow::int8(),
      birth_month = arrow::int8(),
      birth_year = arrow::int16(),
      sex = arrow::int8(),
      marital_status = arrow::int8(),
      n_child_15 = arrow::int16(),
      n_child_5 = arrow::int16(),
      religion = arrow::int8(),
      permanent = arrow::int8(),
      any_schooling = arrow::int8(),
      education = arrow::int8(),
      education_years = arrow::float32(),
      school = arrow::int8(),
      literacy = arrow::int8(),
      read = arrow::int8(),
      write = arrow::int8(),
      work = arrow::int8(),
      work_type = arrow::int8(),
      nowork_available = arrow::int8(),
      nowork_temporary = arrow::int8(),
      hours_total = arrow::float32(),
      jobs_n = arrow::int8(),
      labor_income_total = arrow::float32(),
      labor_income_total_freq = arrow::int8(),
      nlf_reason = arrow::int8(),
      home_hours_water = arrow::float32(),
      home_hours_fuel = arrow::float32(),
      home_hours_domestic = arrow::float32(),
      work_search = arrow::int8(),
      work_search_duration = arrow::float32(),
      work_search_duration_unit = arrow::int8(),
      work_search_mean = arrow::int8(),
      main_job_ind = arrow::string(),
      main_activity = arrow::string(),
      main_job_occ = arrow::int32(),
      main_job_type = arrow::int8(),
      main_job_usual_hours = arrow::float32(),
      main_job_actual_hours = arrow::float32(),
      main_se_duration = arrow::float32(),
      main_se_duration_unit = arrow::int8(),
      main_se_earnings = arrow::float32(),
      main_se_earnings_freq = arrow::int8(),
      main_se_bookkeeping = arrow::int8(),
      main_se_license = arrow::int8(),
      main_se_loc = arrow::int8(),
      main_se_type = arrow::int8(),
      main_se_vat_tax = arrow::int8(),
      main_se_employees = arrow::float32(),
      main_we_benefits = arrow::int8(),
      main_we_contract = arrow::int8(),
      main_we_duration = arrow::float32(),
      main_we_duration_unit = arrow::int8(),
      main_we_employer = arrow::int8(),
      main_we_firm_size = arrow::int8(),
      main_we_home = arrow::int8(),
      main_we_inkind = arrow::float32(),
      main_we_inkind_freq = arrow::int8(),
      main_we_insurance = arrow::int8(),
      main_we_loc = arrow::int8(),
      main_we_wage = arrow::float32(),
      main_we_wage_freq = arrow::int8(),
      sec_job_ind = arrow::string(),
      sec_job_occ = arrow::int32(),
      sec_job_type = arrow::int8(),
      sec_job_actual_hours = arrow::float32(),
      sec_job_usual_hours = arrow::float32(),
      sec_se_earnings = arrow::float32(),
      sec_se_earnings_freq = arrow::int8(),
      sec_se_type = arrow::int8(),
      sec_we_wage = arrow::float32(),
      sec_we_wage_freq = arrow::int8(),
      sec_we_inkind = arrow::float32(),
      sec_we_inkind_freq = arrow::int8()
    ))
  } else {
    arrow::schema(list(
      survey = arrow::string(),
      year = arrow::int32(),
      country = arrow::string(),
      survey_year = arrow::int16(),
      # survey_period = arrow::string(),
      wgt = arrow::float32(),
      # panel_wgt = arrow::float32(),
      # gadm_1 = arrow::string(),
      # gadm_2 = arrow::string(),
      # ea = arrow::string(),
      # density = arrow::float32(),
      rural = arrow::bool(),
      # id_hh = arrow::string(),
      # id_hh_panel = arrow::string(),
      id_ind = arrow::string(),
      # id_ind_panel = arrow::string(),
      # n_interview = arrow::int32(),
      # n_ind_household = arrow::int16(),
      # position = arrow::string(),
      age = arrow::int32(),
      # birth_day = arrow::int8(),
      # birth_month = arrow::int8(),
      # birth_year = arrow::int16(),
      sex = arrow::bool(),
      marital_status = arrow::string(),
      # n_child_15 = arrow::int16(),
      n_child_5 = arrow::int16(),
      # religion = arrow::string(),
      # permanent = arrow::bool(),
      # any_schooling = arrow::bool(),
      education = arrow::string(),
      # education_years = arrow::float32(),
      # school = arrow::bool(),
      # literacy = arrow::bool(),
      # read = arrow::bool(),
      # write = arrow::bool(),
      work = arrow::bool(),
      # work_type = arrow::string(),
      # nowork_available = arrow::bool(),
      # nowork_temporary = arrow::bool(),
      # hours_total = arrow::float32(),
      # jobs_n = arrow::int8(),
      # labor_income_total = arrow::float32(),
      # nlf_reason = arrow::string(),
      # home_hours_water = arrow::float32(),
      # home_hours_fuel = arrow::float32(),
      # home_hours_domestic = arrow::float32(),
      work_search = arrow::bool(),
      # work_search_duration = arrow::float32(),
      # work_search_mean = arrow::string(),
      main_job_ind = arrow::string(),
      main_activity = arrow::string()
      # main_job_occ = arrow::int32(),
      # main_job_type = arrow::string(),
      # main_job_usual_hours = arrow::float32(),
      # main_job_actual_hours = arrow::float32(),
      # main_job_pay = arrow::float32()
      # main_job_loc = arrow::string(),
      # main_job_duration = arrow::float32(),
      # main_we_benefits = arrow::bool(),
      # main_we_contract = arrow::bool(),
      # main_we_employer = arrow::bool(),
      # main_we_firm_size = arrow::string(),
      # main_we_home = arrow::bool(),
      # main_we_inkind = arrow::float32(),
      # main_we_insurance = arrow::bool(),
      # main_se_bookkeeping = arrow::bool(),
      # main_se_license = arrow::bool(),
      # main_se_vat_tax = arrow::bool(),
      # main_se_employees = arrow::int32(),
      # sec_job_ind = arrow::string(),
      # sec_job_occ = arrow::int32(),
      # sec_job_type = arrow::string(),
      # sec_job_actual_hours = arrow::float32(),
      # sec_job_usual_hours = arrow::float32(),
      # sec_job_pay = arrow::float32(),
      # sec_we_inkind = arrow::float32(),
      # sec_se_type = arrow::bool()
    ))
  }
}
